version: '3.8'
services:
  db_postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Kambing04
      - POSTGRES_USER=bagasunix
      - POSTGRES_DB=kuyngetrip
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     db_postgres:
  #       condition: service_healthy
  #   links:
  #     - db_postgres
  #   environment:
  #     - DB_HOST=db_postgres

volumes:
  postgres-data: