version: '3.8'
services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  vault:
    image: vault:latest
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/policies:/vault/policies

volumes:
  postgres-data: