-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cities
(
    id smallint NOT NULL DEFAULT nextval('cities_id_seq'::regclass),
    province_id smallint NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    latitude numeric,
    longitude numeric,
    accuracy numeric,
    postal_codes text COLLATE pg_catalog."default",
    CONSTRAINT cities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coordinates
(
    latitude numeric,
    longitude numeric,
    accuracy numeric
);

CREATE TABLE IF NOT EXISTS public.countries
(
    id smallint NOT NULL DEFAULT nextval('countries_id_seq'::regclass),
    name character varying(200) COLLATE pg_catalog."default",
    latitude numeric,
    longitude numeric,
    accuracy numeric,
    CONSTRAINT countries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.destinations
(
    id uuid NOT NULL,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    tour_id uuid NOT NULL,
    destination_name text COLLATE pg_catalog."default" NOT NULL,
    destination_description text COLLATE pg_catalog."default",
    name character varying(200) COLLATE pg_catalog."default",
    latitude numeric,
    longitude numeric,
    accuracy numeric,
    country_id smallint NOT NULL,
    postal_codes text COLLATE pg_catalog."default",
    province_id smallint NOT NULL,
    city_id smallint NOT NULL,
    sub_district_id integer NOT NULL,
    delete smallint,
    deleted_by uuid,
    deleted_at timestamp with time zone,
    CONSTRAINT destinations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.participants
(
    id uuid NOT NULL,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    user_id uuid NOT NULL,
    registration_date timestamp with time zone,
    tour_schedule_id uuid NOT NULL,
    CONSTRAINT participants_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id uuid NOT NULL,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    tour_schedule_id uuid NOT NULL,
    participant_id uuid NOT NULL,
    payment_date timestamp with time zone,
    payment_status character varying(10) COLLATE pg_catalog."default",
    payment_amount numeric(10, 2),
    payment_method character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.provinces
(
    id smallint NOT NULL DEFAULT nextval('provinces_id_seq'::regclass),
    country_id smallint NOT NULL,
    name character varying(50) COLLATE pg_catalog."default",
    latitude numeric,
    longitude numeric,
    accuracy numeric,
    postal_codes text COLLATE pg_catalog."default",
    CONSTRAINT provinces_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sub_districts
(
    id integer NOT NULL DEFAULT nextval('sub_districts_id_seq'::regclass),
    city_id smallint NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    latitude numeric,
    longitude numeric,
    accuracy numeric,
    postal_codes text COLLATE pg_catalog."default",
    CONSTRAINT sub_districts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tour_images
(
    id uuid NOT NULL,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    destination_id uuid NOT NULL,
    image_name text COLLATE pg_catalog."default",
    image_path text COLLATE pg_catalog."default",
    image_description text COLLATE pg_catalog."default",
    CONSTRAINT tour_images_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tour_reviews
(
    id uuid NOT NULL,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    tour_schedule_id text COLLATE pg_catalog."default" NOT NULL,
    participant_id uuid NOT NULL,
    rating numeric(2, 1),
    review_text text COLLATE pg_catalog."default",
    delete smallint,
    deleted_by uuid,
    deleted_at timestamp with time zone,
    CONSTRAINT tour_reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tour_schedules
(
    id uuid NOT NULL,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    tour_id uuid NOT NULL,
    tour_date timestamp with time zone,
    capacity bigint NOT NULL,
    delete smallint,
    deleted_by uuid,
    deleted_at timestamp with time zone,
    CONSTRAINT tour_schedules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tours
(
    id uuid NOT NULL,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    tour_guide_id uuid NOT NULL,
    tour_name text COLLATE pg_catalog."default" NOT NULL,
    tour_description text COLLATE pg_catalog."default",
    tour_price numeric NOT NULL,
    delete smallint,
    deleted_by uuid,
    deleted_at timestamp with time zone,
    CONSTRAINT tours_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_details
(
    user_detail_id uuid NOT NULL,
    user_id uuid NOT NULL,
    full_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dob timestamp with time zone,
    pob text COLLATE pg_catalog."default",
    phone character varying(12) COLLATE pg_catalog."default" NOT NULL,
    sex smallint,
    identification_type text COLLATE pg_catalog."default",
    identification_number text COLLATE pg_catalog."default",
    identification_image text COLLATE pg_catalog."default",
    village_id bigint,
    sub_district_id integer,
    city_id smallint,
    province_id smallint,
    verified smallint,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    CONSTRAINT user_details_pkey PRIMARY KEY (user_detail_id),
    CONSTRAINT idx_user_details_phone UNIQUE (phone)
);

COMMENT ON COLUMN public.user_details.sex
    IS '1-male,2-female';

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    created_by uuid,
    created_at uuid,
    updated_by uuid,
    updated_at timestamp with time zone,
    user_name text COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    user_type text COLLATE pg_catalog."default",
    picture text COLLATE pg_catalog."default",
    active character varying(1) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT idx_users_email UNIQUE (email)
);

COMMENT ON COLUMN public.users.active
    IS '0 - NonActive, 1 - Active, 2 - Pending, 3 - Suspended';

CREATE TABLE IF NOT EXISTS public.villages
(
    id bigint NOT NULL DEFAULT nextval('villages_id_seq'::regclass),
    sub_district_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    latitude numeric,
    longitude numeric,
    accuracy numeric,
    postal_codes character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT villages_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cities
    ADD CONSTRAINT fk_cities_province FOREIGN KEY (province_id)
    REFERENCES public.provinces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.destinations
    ADD CONSTRAINT fk_destinations_city FOREIGN KEY (city_id)
    REFERENCES public.cities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.destinations
    ADD CONSTRAINT fk_destinations_country FOREIGN KEY (country_id)
    REFERENCES public.countries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.destinations
    ADD CONSTRAINT fk_destinations_province FOREIGN KEY (province_id)
    REFERENCES public.provinces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.destinations
    ADD CONSTRAINT fk_destinations_sub_district FOREIGN KEY (sub_district_id)
    REFERENCES public.sub_districts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.destinations
    ADD CONSTRAINT fk_destinations_tour FOREIGN KEY (tour_id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.destinations
    ADD CONSTRAINT fk_tours_destinations FOREIGN KEY (id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS destinations_pkey
    ON public.destinations(id);


ALTER TABLE IF EXISTS public.participants
    ADD CONSTRAINT fk_participants_user FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.participants
    ADD CONSTRAINT fk_tour_schedules_participants FOREIGN KEY (tour_schedule_id)
    REFERENCES public.tour_schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_participants_payment FOREIGN KEY (participant_id)
    REFERENCES public.participants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT fk_payments_tour_schedule FOREIGN KEY (tour_schedule_id)
    REFERENCES public.tour_schedules (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.provinces
    ADD CONSTRAINT fk_provinces_country FOREIGN KEY (country_id)
    REFERENCES public.countries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sub_districts
    ADD CONSTRAINT fk_sub_districts_city FOREIGN KEY (city_id)
    REFERENCES public.cities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tour_images
    ADD CONSTRAINT fk_destinations_image_destination FOREIGN KEY (destination_id)
    REFERENCES public.destinations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tour_reviews
    ADD CONSTRAINT fk_participants_tour_review FOREIGN KEY (participant_id)
    REFERENCES public.participants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tour_reviews
    ADD CONSTRAINT fk_tour_reviews_participant FOREIGN KEY (participant_id)
    REFERENCES public.participants (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tour_reviews
    ADD CONSTRAINT fk_tours_reviews FOREIGN KEY (id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS tour_reviews_pkey
    ON public.tour_reviews(id);


ALTER TABLE IF EXISTS public.tour_schedules
    ADD CONSTRAINT fk_tour_reviews_tour_schedule FOREIGN KEY (tour_id)
    REFERENCES public.tour_reviews (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tour_schedules
    ADD CONSTRAINT fk_tour_schedules_tour FOREIGN KEY (tour_id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tour_schedules
    ADD CONSTRAINT fk_tours_tour_schedule FOREIGN KEY (id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS tour_schedules_pkey
    ON public.tour_schedules(id);


ALTER TABLE IF EXISTS public.tours
    ADD CONSTRAINT fk_tours_user FOREIGN KEY (tour_guide_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.user_details
    ADD CONSTRAINT fk_user_details_city FOREIGN KEY (city_id)
    REFERENCES public.cities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_details
    ADD CONSTRAINT fk_user_details_province FOREIGN KEY (province_id)
    REFERENCES public.provinces (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_details
    ADD CONSTRAINT fk_user_details_sub_district FOREIGN KEY (sub_district_id)
    REFERENCES public.sub_districts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_details
    ADD CONSTRAINT fk_user_details_village FOREIGN KEY (village_id)
    REFERENCES public.villages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_details
    ADD CONSTRAINT fk_users_user_detail FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.villages
    ADD CONSTRAINT fk_villages_sub_district FOREIGN KEY (sub_district_id)
    REFERENCES public.sub_districts (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;